#!/usr/bin/env bash

ERROUT() {
	printf "%b" "$@"
} >&2

USAGE() {
	ERROUT "usage: %s <newdir>\n" $(basename $0)
}

# GENALBUM(thisph, startph, prevph, nextph, lastph)
GENALBUM() {
	THISPH="../$1"
	STRTPH="${2%.*}.html"
	PREVPH="${3%.*}.html"
	NEXTPH="${4%.*}.html"
	LASTPH="${5%.*}.html"

	if [ -z "$3" ] 
	then
		PREVLINE='<TD> Prev </TD>'
	else
		PREVLINE='<TD><A HREF="'$PREVPH'"> Prev </A></TD>'
	fi
	if [ -z "$4" ] 
	then
		NEXTLINE='<TD> Next </TD>'
	else
		NEXTLINE='<TD><A HREF="'$NEXTPH'"> Next </A></TD>'
	fi

cat <<EOF
<HTML>
<HEAD><TITLE>$THISPH</TITLE></HEAD>
<BODY>
	<H2>$THISPH</H2>
	<TABLE WIDTH="25%">
		<TR>
			<TD><A HREF="$STRTPH"> First </A></TD>
			$PREVLINE
			$NEXTLINE
			<TD><A HREF="$LASTPH"> LAST </A></TD>
		</TR>
	</TABLE> 
	<IMG SRC="$THISPH" alt="$THISPH" BORDER="1" VSPACE="4" HSAPCE="4" WIDTH="800" HEIGHT="600" />
</BODY>
</HTML>
EOF
} 


if (( $# != 1 )) 
then
	USAGE
	exit -1
fi

ALBUM="$1"
if [ -d "${ALBUM}" ]
then
	ERROUT "Directory [%s] already exists.\n" ${ALBUM}
	USAGE
	exit -2
else
	mkdir "$ALBUM"
fi

cd "$ALBUM"

FIRST=""
PREV=""
LAST="last"

while read PHOTO
do
	if [ -z "${CURRENT}" ]
	then
		CURRENT="$PHOTO"
		FIRST="$PHOTO"
		continue
	fi

	PHILE=$(basename "${CURRENT}")
	GENALBUM "$CURRENT" "$FIRST" "$PREV" "$PHOTO" "$LAST" > "${PHILE%.*}.html"

	PREV="$CURRENT"
	CURRENT="$PHOTO"
done

PHILE=$(basename "$CURRENT")
GENALBUM "$CURRENT" "$FIRST" "$PREV" "" "$LAST" > "${PHILE%.*}.html"

ln -s "${PHILE%.*}.html" ./last.html
ln -s "${FIRST%.*}.html" ./index.html



